// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: frost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block contains a block data
type FrostMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Number  string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *FrostMessage) Reset() {
	*x = FrostMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrostMessage) ProtoMessage() {}

func (x *FrostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_frost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrostMessage.ProtoReflect.Descriptor instead.
func (*FrostMessage) Descriptor() ([]byte, []int) {
	return file_frost_proto_rawDescGZIP(), []int{0}
}

func (x *FrostMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FrostMessage) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_frost_proto protoreflect.FileDescriptor

var file_frost_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x22, 0x40, 0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x66, 0x72, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frost_proto_rawDescOnce sync.Once
	file_frost_proto_rawDescData = file_frost_proto_rawDesc
)

func file_frost_proto_rawDescGZIP() []byte {
	file_frost_proto_rawDescOnce.Do(func() {
		file_frost_proto_rawDescData = protoimpl.X.CompressGZIP(file_frost_proto_rawDescData)
	})
	return file_frost_proto_rawDescData
}

var file_frost_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frost_proto_goTypes = []interface{}{
	(*FrostMessage)(nil), // 0: v1.FrostMessage
}
var file_frost_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frost_proto_init() }
func file_frost_proto_init() {
	if File_frost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrostMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frost_proto_goTypes,
		DependencyIndexes: file_frost_proto_depIdxs,
		MessageInfos:      file_frost_proto_msgTypes,
	}.Build()
	File_frost_proto = out.File
	file_frost_proto_rawDesc = nil
	file_frost_proto_goTypes = nil
	file_frost_proto_depIdxs = nil
}
