---
name: Lint
on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - 'develop'
      - 'release/**'
    tags-ignore:
      - 'v*'
    paths:
      - '**.go'
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  golangci_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      
      - name: Set Github PAT for private deps
        run: git config --global url."https://${{ secrets.ROBOT_TOPOSWARE_PRIV_REPOS_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
